# Generated by Django 2.2.4 on 2019-09-27 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper', models.TextField(default='https://docs.djangoproject.com/en/2.2/topics/db/models/', verbose_name='link to the paper')),
                ('category', models.CharField(choices=[('L', 'Logistica'), ('H', 'Hospitales'), ('A', 'Ambiente')], default='L', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_title', models.CharField(max_length=100)),
                ('presentation_content', models.TextField()),
                ('postDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation_ImageOnline',
            fields=[
                ('presentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Presentation')),
                ('ImageOnline_title', models.CharField(max_length=100)),
                ('ImageOnline_link', models.TextField(default='https://i.pinimg.com/236x/bb/16/5c/bb165c8fcecf107962691450d7505dd3--world-cutest-dog-cutest-dogs.jpg', verbose_name='link to the image')),
            ],
            bases=('blog.presentation',),
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDetail_title', models.CharField(max_length=100)),
                ('postDetail_content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
