# Generated by Django 2.2.4 on 2019-09-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='postDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostDetail'),
        ),
    ]
