# Generated by Django 2.2.4 on 2019-09-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190927_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation_imageonline',
            name='ImageOnline_title',
        ),
    ]
