# Generated by Django 2.2.4 on 2019-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_presentation_imageonline_imageonline_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation_imageonline',
            name='ImageOnline_title',
            field=models.CharField(default='aloh', max_length=100),
        ),
    ]
