# Generated by Django 2.2.4 on 2019-09-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_presentation_imageonline_imageonline_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation_imageonline',
            name='ImageOnline_title',
        ),
    ]
